name: Workflow Evento
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:	    
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      pull-requests: write
    steps:
      - name: Adicionando funcionalidade
        run: echo "Teste de action"
