name: workflow concorrencia
run-name: Workflow Concorrencia ${{ github.rum_number }}
on:
  push:

concurrency: 
  group: ${{ inputs.ref }}-${{ github.workflow}}
  cancel-in-progress: true

jobs:
  exemplo-fluxo-execucao-01:
    runs-on: ubuntu-latest
    steps:
      - name: Execução do job teste
        run: |
          sleep 120;
          echo "Action executada job 01"
  exemplo-fluxo-execucao-02:
    runs-on: ubuntu-latest
    needs: [exemplo-fluxo-execucao-01]
    concurrency: ${{ inputs.chave }}
    steps:
      - name: Execução do job teste
        run: |
          sleep 120;
          echo "Action executada job 02"
   
