name: workflow Events
on:
  push:
jobs:
    apenas-main:
      runs-on: ubuntu-latest
      steps:
        - name: Executar na main
          run: echo "Executando comando na main"
    todos:
      runs-on: ubuntu=latest
      steps:
        - name: Execução em Feature
          if: ${{contains(github.ref =='refs/heads/Feature') }}
          run: exho "Execução em Feature"
        - name: Execução em HotFix
          if: ${{contains(github.ref =='refs/heads/hotfix')}}
          run: echo "Execução em Hotfix"
        - name: Execução em Main
          if: ${{github.ref =='refs/heads/main'}} 
          run: echo "Execução em Main"
          
