name: workflow Evento
on:
  push:
    branches: ["main", "feature/*"]
    paths:
      - "src/**"
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Fake Teste
        run: echo "Fake teste de ambiente"
