name: workflow Events
on:
  push:
jobs:
    apenas-main:
      name: Esse Jobs so executa na  ranch main
      runs-on: ubuntu-latest
      steps:
        - name: Executar na main
          run: scho "Executando comando na main"
          


